# Generated by Django 6.0.4 on 2026-06-17 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmmembership",
            name="can_manage_finance",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="farmmembership",
            name="can_manage_inventory",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="farmmembership",
            name="can_manage_sales",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="farmmembership",
            name="can_manage_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="farmmembership",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="active_membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_users",
                to="accounts.farmmembership",
            ),
        ),
        migrations.AlterField(
            model_name="farmmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("manager", "Manager"),
                    ("staff", "Staff"),
                    ("finance", "Finance"),
                    ("viewer", "Viewer"),
                ],
                default="staff",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Platform Admin"),
                    ("owner", "Farm Owner"),
                    ("manager", "Farm Manager"),
                    ("staff", "Farm Staff"),
                    ("finance", "Finance"),
                    ("viewer", "Viewer"),
                    ("customer", "Marketplace Customer"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="farmmembership",
            index=models.Index(
                fields=["farm", "role"], name="accounts_fa_farm_id_0f89d9_idx"
            ),
        ),
    ]
