# Generated by Django 6.0.4 on 2026-05-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="bulk_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="bulk_quantity",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="live_type",
            field=models.CharField(
                blank=True,
                choices=[("broiler", "Broiler"), ("layer", "Layer")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="selling_unit",
            field=models.CharField(
                choices=[
                    ("unit", "Per Unit"),
                    ("kg", "Per Kilogram"),
                    ("tray", "Per Tray"),
                ],
                default="unit",
                max_length=20,
            ),
        ),
    ]
