# Generated by Django 6.0.4 on 2026-05-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="expense_source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("inventory", "Inventory"),
                    ("system", "System Generated"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("feed", "Feed"),
                    ("medicine", "Medication/Vaccines"),
                    ("equipment", "Equipment/Tools"),
                    ("labor", "Labor"),
                    ("utilities", "Utilities"),
                    ("fuel", "Fuel"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
