# Generated by Django 6.0.4 on 2026-06-15

from django.db import migrations, models


def copy_units(apps, schema_editor):
    InventoryItem = apps.get_model("inventory", "InventoryItem")

    for item in InventoryItem.objects.all():

        old = getattr(item, "unit_of_measure", None)

        if old:
            item.inventory_unit = old
            item.purchase_unit = old
        else:
            item.inventory_unit = "KG"
            item.purchase_unit = "KG"

        item.save(
            update_fields=[
                "inventory_unit",
                "purchase_unit",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0002_alter_stocklog_unit_price_at_time_inventorypurchase",
        ),
    ]

    operations = [

        # ADD FIRST
        migrations.AddField(
            model_name="inventoryitem",
            name="inventory_unit",
            field=models.CharField(
                max_length=20,
                default="KG",
                choices=[
                    ("KG", "Kilogram"),
                    ("G", "Gram"),
                    ("MG", "Milligram"),
                    ("L", "Litre"),
                    ("ML", "Millilitre"),
                    ("BAG", "Bag"),
                    ("BOTTLE", "Bottle"),
                    ("BOX", "Box"),
                    ("UNIT", "Unit"),
                ],
            ),
        ),

        migrations.AddField(
            model_name="inventoryitem",
            name="purchase_unit",
            field=models.CharField(
                max_length=20,
                default="KG",
                choices=[
                    ("KG", "Kilogram"),
                    ("G", "Gram"),
                    ("MG", "Milligram"),
                    ("L", "Litre"),
                    ("ML", "Millilitre"),
                    ("BAG", "Bag"),
                    ("BOTTLE", "Bottle"),
                    ("BOX", "Box"),
                    ("UNIT", "Unit"),
                ],
            ),
        ),

        migrations.AddField(
            model_name="inventoryitem",
            name="conversion_factor",
            field=models.DecimalField(
                max_digits=12,
                decimal_places=4,
                default=1,
            ),
        ),

        # COPY DATA
        migrations.RunPython(
            copy_units,
            migrations.RunPython.noop,
        ),

        # REMOVE LAST
        migrations.RemoveField(
            model_name="inventoryitem",
            name="unit_of_measure",
        ),

        migrations.AlterField(
            model_name="inventoryitem",
            name="category",
            field=models.CharField(
                max_length=30,
                default="feed",
            ),
        ),

        migrations.AlterField(
            model_name="inventoryitem",
            name="current_level",
            field=models.DecimalField(
                max_digits=14,
                decimal_places=2,
                default=0,
            ),
        ),

        migrations.AlterField(
            model_name="inventoryitem",
            name="cost_per_unit",
            field=models.DecimalField(
                max_digits=12,
                decimal_places=2,
                default=0,
            ),
        ),

        migrations.AlterField(
            model_name="inventoryitem",
            name="min_stock_level",
            field=models.DecimalField(
                max_digits=12,
                decimal_places=2,
                default=10,
            ),
        ),
    ]