# Generated by Django 6.0.4 on 2026-06-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_stocklog_unit_price_at_time_inventorypurchase"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventoryitem",
            name="unit_of_measure",
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="conversion_factor",
            field=models.DecimalField(decimal_places=4, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="inventory_unit",
            field=models.CharField(
                choices=[
                    ("KG", "Kilogram"),
                    ("G", "Gram"),
                    ("MG", "Milligram"),
                    ("L", "Litre"),
                    ("ML", "Millilitre"),
                    ("BAG", "Bag"),
                    ("BOTTLE", "Bottle"),
                    ("BOX", "Box"),
                    ("UNIT", "Unit"),
                ],
                default="KG",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="purchase_unit",
            field=models.CharField(
                choices=[
                    ("KG", "Kilogram"),
                    ("G", "Gram"),
                    ("MG", "Milligram"),
                    ("L", "Litre"),
                    ("ML", "Millilitre"),
                    ("BAG", "Bag"),
                    ("BOTTLE", "Bottle"),
                    ("BOX", "Box"),
                    ("UNIT", "Unit"),
                ],
                default="KG",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="category",
            field=models.CharField(default="feed", max_length=30),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="cost_per_unit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="current_level",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="min_stock_level",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=12),
        ),
        migrations.AlterField(
            model_name="inventorypurchase",
            name="quantity",
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name="inventorypurchase",
            name="total_cost",
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name="inventorypurchase",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="quantity",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="stocklog",
            name="quantity_changed",
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name="stocklog",
            name="unit_price_at_time",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
