# Generated by Django 6.0.4 on 2026-05-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
