# Generated by Django 6.0.4 on 2026-05-20 15:28

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("flock", "0002_flockbatch_flock_type"),
        ("products", "0003_product_bulk_price_product_bulk_quantity_and_more"),
        ("sales", "0002_alter_orderitem_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="credit_limit",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="customer",
            name="phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sales.customer",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="farm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="accounts.farm",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="flock.flockbatch",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="cost_per_unit",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price_per_unit",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[("cash", "Cash"), ("card", "Card"), ("transfer", "Transfer")],
                default="cash",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="reference",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
    ]
