# Generated by Django 6.0.4 on 2026-05-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_pendingorder_pendingorderitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="pendingorder",
            name="delivery_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pendingorder",
            name="delivery_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
