# Generated by Django 6.0.4 on 2026-05-26 08:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flock", "0002_flockbatch_flock_type"),
        ("products", "0003_product_bulk_price_product_bulk_quantity_and_more"),
        ("sales", "0006_alter_order_customer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="order",
            old_name="cost_amount",
            new_name="balance_due",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="paid_amount",
            new_name="subtotal",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="total_amount",
            new_name="total_paid",
        ),
        migrations.RenameField(
            model_name="pendingorderitem",
            old_name="order",
            new_name="pending_order",
        ),
        migrations.RemoveField(
            model_name="order",
            name="is_credit",
        ),
        migrations.RemoveField(
            model_name="pendingorderitem",
            name="quantity_fulfilled",
        ),
        migrations.AddField(
            model_name="order",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
                model_name='order',
                name='order_number',
                field=models.CharField(
                    blank=True,
                    null=True,
                    max_length=50,
                ),
            ),
        
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Unpaid"),
                    ("partial", "Partial"),
                    ("paid", "Paid"),
                ],
                default="unpaid",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pendingorderitem",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="flock.flockbatch",
            ),
        ),
        migrations.AddField(
            model_name="pendingorderitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pendingorderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.product",
            ),
        ),
    ]
