# Generated by Django 6.0.4 on 2026-05-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0007_alter_order_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="pendingorder",
            name="order_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
