# Generated by Django 6.0.4 on 2026-05-26 12:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0008_alter_order_order_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingorderitem",
            name="quantity_fulfilled",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
    ]
