# Generated by Django 6.0.4 on 2026-05-26 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0009_pendingorderitem_quantity_fulfilled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pendingorder",
            name="total_amount",
        ),
    ]
