# Generated by Django 6.0.4 on 2026-05-19 16:25

import datetime
import django.db.models.deletion
import flock.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlockBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("batch_number", models.CharField(blank=True, max_length=50)),
                ("breed", models.CharField(blank=True, max_length=100)),
                ("quantity_received", models.PositiveIntegerField()),
                ("acquisition_date", models.DateField(default=datetime.date.today)),
                ("status", models.CharField(default="active", max_length=20)),
                (
                    "chick_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "selling_price_per_bird",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=flock.models.batch_image_path
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="accounts.farm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
                ("mortality", models.PositiveIntegerField(default=0)),
                (
                    "feed_used_kg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "flock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_records",
                        to="flock.flockbatch",
                    ),
                ),
            ],
            options={
                "unique_together": {("flock", "date")},
            },
        ),
    ]
