# Generated by Django 6.0.4 on 2026-05-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flock", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flockbatch",
            name="flock_type",
            field=models.CharField(
                choices=[("broiler", "Broiler"), ("layer", "Layer")],
                default="broiler",
                max_length=20,
            ),
        ),
    ]
