# Generated by Django 6.0.4 on 2026-05-29 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flock", "0003_stockadjustment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stockadjustment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="stockadjustment",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stockadjustment",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stockadjustment",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_stock_adjustments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stockadjustment",
            name="stock_after",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="stockadjustment",
            name="stock_before",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="stockadjustment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_stock_adjustments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
